### ISSUE TITLE
Remove lock-related information when done with a job

### ISSUE THREAD

**Issue by tschoppi** [sitrox/workhorse#16]
When a Job is completed (either succeeded or failed), the `locked_at` and `locked_by` attributes of `DbJob` should be reset to `nil`.

**Comment by tschoppi** [comment]
Same with the attribute `locked_at`.

**Comment by remofritzsche** [comment]
Don't these fields provide useful debugging data when being preserved? Even though a job is completed, it has still been locked before and I think this information should probably persist.

**Comment by tschoppi** [comment]
Consider the case where a job has failed and you want to run it again. There are multiple ways to achieve that, none of which are documented either in our README or FAQ.

The most basic way is to change the status from `failed` back to `waiting` in the database. However, re-locking the job for the execution the second time around will fail because the `locked_*` fields are already set. Thus, when resetting in the database, you also have to set those fields although they have nothing to do with the status of the job, which is slightly suboptimal.

The higher-level way of resetting within Ruby is “not supported” and would require some form of API. In this regard, it would be very nice to have ways to do via the CLI:

1. List all failed jobs
2. Restart jobs (via parameter)

The _high road_ would take more time to implement. In light of this, and assuming that the `locked_*` fields provide marginally useful information upon completion of a job (be it successful or not), I thought it would be acceptable to reset those fields in the db at that point.

**Comment by remofritzsche** [comment]
Thanks for your inputs. As discussed, we've decided to take the *high road* and implement / document a simple API for retrieving and resetting database jobs. Please see the PR attached. Thanks for your review. Especially the new documentation may need some rework to be as concise as possible.

**Comment by tschoppi** [comment]
This was addressed in PR #17.
