### ISSUE TITLE
Random test fails on Travis

### ISSUE THREAD

**Issue by remofritzsche** [sitrox/workhorse#19]
Some tests randomly fail when executed on travis. On our local development machines all tests run successfully. Probably the sleep timings are off on travis / some things take longer than on our local development machines. We should tweak these tests so that they work every time.

**Comment by Adrian-Hirt** [comment]
I migrated the tests from the (now defunct) Travis.org to Github Actions, where all the tests for the following rubies pass:

* 2.5.1
* 2.6.2
* 2.7.1
* 3.0.1

I think we should keep an eye on the tests, but for now I think we can close this issue. Any objections @remofritzsche?

**Comment by remofritzsche** [comment]
Perfect, many thanks for the migration. This is fine for me.
