### ISSUE TITLE
Pass db_job to on_exception block

### ISSUE THREAD

**Issue by tschoppi** [sitrox/workhorse#23]
In order to handle exceptions in a granular fashion, for instance for different queues, we should investigate if passing the `db_job` to `on_exception` in addition to the exception itself would be a sensible approach moving forward.

As outlined above, that would look something like this:
```ruby
# Workhorse::Worker
def perform(db_job)
  # … doing things with db_job
rescue Exception => e
  Workhorse.on_exception.call(e, db_job)
end
```

This requires all `on_exception` blocks configured to accept the second parameter, thus rendering the change backwards-incompatible.

**Comment by remofritzsche** [comment]
Good idea, thanks for the hint. I'll have a look at it.

**Comment by sudoremo** [comment]
> This requires all on_exception blocks configured to accept the second parameter, thus rendering the change backwards-incompatible.

This is the reason we have decided against making this change. But thanks for your valuable input, it is a good idea.
